spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/demodb?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    driverClassName: com.mysql.cj.jdbc.Driver


#  ?????index.html????Config???????????
  web:
    resources:
      static-locations: classpath:/templates/,classpath:/static/

  #????????,
  mybatis:
    configuration:
      map-underscore-to-camel-case: true

#  mybatis:
#    mapper-locations: classpath:mapper/*.xml  #??????
#    type-aliases-package: org.scut.java2022.oyz.dao #?????